Search:
    path:  /search
    defaults: { _controller: AppBundle\Controller\MessagesController::searchAction }
    requirements:
        _method: GET

save:
    path:  /save
    defaults: { _controller: AppBundle\Controller\MessagesController::saveAction }
    requirements:
        _method: GET



