landing_homepage:
    path:     /
    defaults: { _controller: LandingBundle:Default:index }
    requirements:
        _method: GET

Search:
    path:  /search
    defaults: { _controller: AppBundle\Controller\MessagesController::searchAction }
    requirements:
        _method: GET
index:
    path:  /index
    defaults: { _controller: AppBundle\Controller\MessagesController::indexAction }
    requirements:
        _method: GET
pay:
    path:  /pay
    defaults: { _controller: AppBundle\Controller\MessagesController::generatePayAddressAction }
    requirements:
        _method: GET
validatePay:
    path:  /validatePay
    defaults: { _controller: AppBundle\Controller\MessagesController::validatePayAction }
    requirements:
        _method: GET
saveDataDirectly:
    path:  /save
    defaults: { _controller: AppBundle\Controller\MessagesController::saveAction }
    requirements:
        _method: GET
find:
    path:  /find
    defaults: { _controller: AppBundle\Controller\MessagesController::findAction }
    requirements:
        _method: GET